#!/usr/bin/env python3
"""
Demo script showing the new sort toggle functionality
"""

print("=== TFM Sort Toggle Feature Demo ===")
print()
print("The sort keys (1, 2, 3) now have enhanced functionality:")
print()
print("• Press '1' to sort by name")
print("  - If already sorting by name, toggles reverse mode")
print("• Press '2' to sort by size") 
print("  - If already sorting by size, toggles reverse mode")
print("• Press '3' to sort by date")
print("  - If already sorting by date, toggles reverse mode")
print()
print("Example workflow:")
print("1. Start with default name sorting (A→Z)")
print("2. Press '1' → Toggle to reverse name sorting (Z→A)")
print("3. Press '1' → Toggle back to normal name sorting (A→Z)")
print("4. Press '2' → Switch to size sorting (small→large)")
print("5. Press '2' → Toggle to reverse size sorting (large→small)")
print("6. Press '1' → Switch back to name sorting (keeps current reverse setting)")
print()
print("This makes it much faster to toggle between normal and reverse")
print("sorting! The old 'r/R' keys are no longer needed.")
print()
print("To test this feature, run the TFM application and try pressing")
print("the 1, 2, and 3 keys in different combinations.")
print()
print("Note: The sort menu (accessed with 's' key) still provides")
print("a reverse option for users who prefer the menu interface.")