#!/bin/bash
#
# TFM DMG Installer Creation Script
#
# This script creates a distributable DMG installer for TFM.app
#

set -e  # Exit on error

# ============================================================================
# Configuration
# ============================================================================

# Determine project root (parent of macos_app directory)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Build paths
BUILD_DIR="${SCRIPT_DIR}/build"
APP_NAME="TFM"
APP_BUNDLE="${BUILD_DIR}/${APP_NAME}.app"

# DMG configuration
DMG_TEMP_DIR="${BUILD_DIR}/dmg_temp"
DMG_NAME="TFM"
VOLUME_NAME="TFM Installer"

# Version number (can be overridden by environment variable)
VERSION="${VERSION:-0.99}"

# Code signing / notarization (optional; same variables as build.sh).
# CODESIGN_IDENTITY signs the finished DMG; NOTARY_PROFILE (a notarytool
# keychain profile) additionally notarizes and staples it. Leave both unset for
# an unsigned development DMG.
CODESIGN_IDENTITY="${CODESIGN_IDENTITY:-}"
NOTARY_PROFILE="${NOTARY_PROFILE:-}"

# ============================================================================
# Helper Functions
# ============================================================================

log_info() {
    echo "[INFO] $1"
}

log_error() {
    echo "[ERROR] $1" >&2
}

check_app_exists() {
    if [ ! -d "${APP_BUNDLE}" ]; then
        log_error "TFM.app not found at ${APP_BUNDLE}"
        log_error "Please run build.sh first to create the app bundle"
        exit 1
    fi
}

extract_version_from_plist() {
    # Try to extract version from built Info.plist
    local plist="${APP_BUNDLE}/Contents/Info.plist"
    if [ -f "${plist}" ]; then
        local version=$(defaults read "${plist}" CFBundleShortVersionString 2>/dev/null || echo "")
        if [ -n "${version}" ]; then
            echo "${version}"
            return 0
        fi
    fi
    
    # Fallback to VERSION environment variable or default
    echo "${VERSION}"
}

create_install_doc() {
    local install_md="${DMG_TEMP_DIR}/INSTALL.md"
    
    # Check if INSTALL.md exists in project root
    if [ -f "${PROJECT_ROOT}/INSTALL.md" ]; then
        log_info "Copying existing INSTALL.md"
        cp "${PROJECT_ROOT}/INSTALL.md" "${install_md}"
    else
        log_info "Creating INSTALL.md"
        cat > "${install_md}" << 'EOF'
# TFM Installation Instructions

## Installation

1. Drag **TFM.app** to your **Applications** folder
2. Double-click TFM.app to launch
3. If you see a security warning, go to System Preferences > Security & Privacy and click "Open Anyway"

## Usage

- **New Window**: Right-click the Dock icon and select "New Window"
- **Quit**: Press Cmd+Q or right-click the Dock icon and select "Quit"

## Requirements

- macOS 10.13 (High Sierra) or later
- No additional software installation required

## Features

- Dual-pane file manager with native macOS interface
- Full keyboard and mouse support
- S3 bucket browsing support
- Archive file viewing (zip, tar, etc.)
- Syntax-highlighted text viewer
- Directory comparison tool

## Troubleshooting

If TFM fails to launch:

1. Check Console.app for error messages
2. Ensure you're running macOS 10.13 or later
3. Try reinstalling by dragging TFM.app to Trash and reinstalling

For more information, visit: https://github.com/shimomut/tfm

EOF
    fi
}

# ============================================================================
# Main Build Process
# ============================================================================

main() {
    log_info "Starting DMG creation for TFM"
    
    # Check prerequisites
    check_app_exists
    
    # Extract version
    VERSION=$(extract_version_from_plist)
    DMG_FILENAME="${DMG_NAME}-${VERSION}.dmg"
    DMG_PATH="${BUILD_DIR}/${DMG_FILENAME}"
    
    log_info "Creating DMG: ${DMG_FILENAME}"
    log_info "Version: ${VERSION}"
    
    # Clean up any existing DMG temp directory
    if [ -d "${DMG_TEMP_DIR}" ]; then
        log_info "Cleaning up existing DMG temp directory"
        rm -rf "${DMG_TEMP_DIR}"
    fi
    
    # Create temporary DMG directory
    log_info "Creating temporary DMG directory"
    mkdir -p "${DMG_TEMP_DIR}"
    
    # Copy TFM.app to DMG directory
    log_info "Copying TFM.app to DMG directory"
    cp -R "${APP_BUNDLE}" "${DMG_TEMP_DIR}/"
    
    # Create or copy INSTALL.md
    create_install_doc
    
    # Copy LICENSE file
    log_info "Copying LICENSE file"
    if [ -f "${PROJECT_ROOT}/LICENSE" ]; then
        cp "${PROJECT_ROOT}/LICENSE" "${DMG_TEMP_DIR}/"
    else
        log_warning "LICENSE file not found at ${PROJECT_ROOT}/LICENSE"
    fi

    # Surface the generated third-party notices at the DMG root too (it also
    # ships inside the .app bundle's Resources). Generated by build.sh via
    # tools/generate_third_party_notices.py.
    BUNDLE_NOTICES="${APP_BUNDLE}/Contents/Resources/THIRD_PARTY_NOTICES.txt"
    if [ -f "${BUNDLE_NOTICES}" ]; then
        log_info "Copying THIRD_PARTY_NOTICES.txt"
        cp "${BUNDLE_NOTICES}" "${DMG_TEMP_DIR}/"
    else
        log_warning "THIRD_PARTY_NOTICES.txt not found at ${BUNDLE_NOTICES}; run build.sh first"
    fi

    # Remove any existing DMG with the same name
    if [ -f "${DMG_PATH}" ]; then
        log_info "Removing existing DMG"
        rm -f "${DMG_PATH}"
    fi
    
    # Create DMG using hdiutil
    log_info "Creating DMG with hdiutil"
    hdiutil create \
        -volname "${VOLUME_NAME}" \
        -srcfolder "${DMG_TEMP_DIR}" \
        -ov \
        -format UDZO \
        "${DMG_PATH}"
    
    # Clean up temporary directory
    log_info "Cleaning up temporary directory"
    rm -rf "${DMG_TEMP_DIR}"
    
    # Sign and (optionally) notarize the DMG. The .app inside is already signed
    # by build.sh (and, if NOTARY_PROFILE was set then, notarized + stapled).
    # Signing the DMG lets Gatekeeper validate the container; notarizing +
    # stapling the DMG makes a downloaded installer open without warnings even
    # offline.
    if [ -n "${CODESIGN_IDENTITY}" ]; then
        log_info "Signing DMG..."
        codesign --force --timestamp --sign "${CODESIGN_IDENTITY}" "${DMG_PATH}"
        if ! codesign --verify --verbose=2 "${DMG_PATH}"; then
            log_error "DMG signature verification failed"
            exit 1
        fi
        log_info "DMG signed"

        if [ -n "${NOTARY_PROFILE}" ]; then
            log_info "Notarizing DMG (this can take a few minutes)..."
            if xcrun notarytool submit "${DMG_PATH}" \
                    --keychain-profile "${NOTARY_PROFILE}" --wait; then
                xcrun stapler staple "${DMG_PATH}"
                xcrun stapler validate "${DMG_PATH}"
                log_info "DMG notarized and stapled"
            else
                log_error "DMG notarization failed. Inspect the log with:"
                log_error "  xcrun notarytool log <submission-id> --keychain-profile \"${NOTARY_PROFILE}\""
                exit 1
            fi
        else
            log_info "NOTARY_PROFILE not set; DMG signed but not notarized"
        fi
    else
        log_info "CODESIGN_IDENTITY not set; DMG left unsigned (development build)"
    fi

    # Success
    log_info "DMG created successfully: ${DMG_PATH}"
    log_info "Size: $(du -h "${DMG_PATH}" | cut -f1)"

    echo ""
    echo "✓ DMG installer created: ${DMG_FILENAME}"
    echo "  Location: ${DMG_PATH}"
    echo ""
}

# Run main function
main "$@"
