#!/usr/bin/env python3
"""Generate the GLSL ES (WebGL) dialect of each background scene from its MSL.

TFM's background scenes (``src/tfm_background_shaders.py``) ship one source per
backend dialect — ``<SCENE>_MSL`` (macOS/Metal), ``<SCENE>_HLSL`` (Windows/D3D),
and now ``<SCENE>_GLSL`` (web/WebGL). Unlike the hand-written HLSL, the GLSL is a
**mechanical transpile of the MSL**, so it is generated by this tool rather than
maintained by hand: tune the MSL, then re-run

    PYTHONPATH=src python tools/generate_shader_glsl.py

to rewrite every ``<SCENE>_GLSL`` block (inserted after its ``<SCENE>_HLSL``) and
add ``"source_glsl"`` to each ``SHADER_KINDS`` entry. The generated GLSL is
committed so the source is reviewable and no transpile runs at import time. The
result targets GLSL ES 3.00 (WebGL2) — real scenes use ``uint`` bit-hashes and
indexed arrays that ES 1.00 forbids — matching PuiKit's ``GLSL_PRELUDE``; run it
through ``glslangValidator`` to confirm each compiles.

The transpile is the fixed MSL→GLSL substitution the scenes are written to allow
(see the module docstring in ``tfm_background_shaders.py``): types, qualifiers,
the entry signature, uniform access, and the handful of dialect-specific
intrinsics. It is deliberately dumb; a scene that outgrows it should be flagged
here, not worked around in the shader.
"""
from __future__ import annotations

import os
import re
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_SRC = os.path.join(os.path.dirname(_HERE), "src")
sys.path.insert(0, _SRC)

import tfm_background_shaders as S  # noqa: E402

SCENES = ["WAVE", "RAIN", "STARFIELD", "GRID", "CONSTELLATION", "DATASTREAM", "HOLOGRAM"]
_TARGET = os.path.join(_SRC, "tfm_background_shaders.py")


def _replace_saturate(src: str) -> str:
    """``saturate(expr)`` -> ``clamp(expr, 0.0, 1.0)`` across balanced parens."""
    out, i = [], 0
    while True:
        j = src.find("saturate(", i)
        if j < 0:
            out.append(src[i:])
            return "".join(out)
        out.append(src[i:j])
        k, depth = j + len("saturate("), 1
        while k < len(src) and depth:
            depth += (src[k] == "(") - (src[k] == ")")
            k += 1
        out.append("clamp(" + src[j + len("saturate("):k - 1] + ", 0.0, 1.0)")
        i = k


def transpile(msl: str) -> str:
    """One scene's MSL fragment source -> its GLSL ES 3.00 equivalent."""
    s = msl
    # Entry signature -> the prototype PuiKit's GLSL_PRELUDE forward-declares.
    s = re.sub(
        r"fragment\s+float4\s+puikit_bg_fragment\s*\(\s*float4\s+pos\s*\[\[position\]\]\s*,"
        r"\s*constant\s+BackgroundUniforms\s*&\s*u\s*\[\[buffer\(0\)\]\]\s*\)",
        "vec4 puikit_bg_fragment(vec2 pos)", s,
    )
    # Uniform struct fields -> the prelude's global uniforms.
    for f in ("resolution", "time", "opacity", "ink", "backdrop"):
        s = s.replace("u." + f, f)
    # Types (matrices before vectors), then storage qualifiers.
    for a, b in (("float2x2", "mat2"), ("float3x3", "mat3"), ("float4x4", "mat4"),
                 ("float2", "vec2"), ("float3", "vec3"), ("float4", "vec4")):
        s = re.sub(r"\b" + a + r"\b", b, s)
    s = s.replace("constant ", "const ").replace("static inline ", "").replace("static ", "")
    # Intrinsics that differ by dialect.
    s = _replace_saturate(s)
    # MSL fmod truncates toward zero; GLSL mod floors, so they disagree on negative
    # operands (scenes wrap possibly-negative indices). Use an exact fmod helper.
    s = re.sub(r"\bfmod\s*\(", "pk_fmod(", s)
    s = re.sub(r"\batan2\s*\(", "atan(", s)
    s = re.sub(r"\brsqrt\s*\(", "inversesqrt(", s)
    s = re.sub(r"\blerp\s*\(", "mix(", s)
    s = re.sub(r"\bfrac\s*\(", "fract(", s)
    # GLSL ES 3.00 has no implicit int->uint (MSL does): a bare integer literal
    # passed as the uint salt of the integer hash needs an explicit 'u' suffix.
    s = re.sub(r"\brnd\(\s*(\w+)\s*,\s*(\d+)\s*\)", r"rnd(\1, \2u)", s)
    if "pk_fmod(" in s:
        s = "float pk_fmod(float a, float b) { return a - b * trunc(a / b); }\n" + s
    return "\n" + s.lstrip("\n")


def main() -> None:
    with open(_TARGET, encoding="utf-8") as fh:
        text = fh.read()

    for name in SCENES:
        glsl = transpile(getattr(S, name + "_MSL"))
        if glsl.count("{") != glsl.count("}"):
            raise SystemExit(f"{name}: brace mismatch after transpile")
        block = f'{name}_GLSL = """{glsl}"""\n'
        if f"{name}_GLSL = " in text:
            # Regenerate in place.
            text = re.sub(rf'(?s){name}_GLSL = """.*?"""\n', block, text)
        else:
            # Insert right after the HLSL twin.
            text = re.sub(rf'(?s)({name}_HLSL = """.*?""")\n',
                          lambda m: m.group(1) + "\n\n" + block, text, count=1)
        # Wire the registry entry (idempotent). Entries end either
        # `..._HLSL, "resolution_scale": ...}` or just `..._HLSL}`, so match the
        # delimiter (a comma or the closing brace) and keep it.
        if f'"source_glsl": {name}_GLSL' not in text:
            text = re.sub(
                rf'("source_hlsl": {name}_HLSL)([,}}])',
                rf'\1, "source_glsl": {name}_GLSL\2', text, count=1)

    with open(_TARGET, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"Wrote {len(SCENES)} GLSL scenes into {os.path.relpath(_TARGET)}")


if __name__ == "__main__":
    main()
